
import React from 'react';


// Do not edit this file
const Button = (props) => {
  return (
    <button name="subject" onClick={props.onClick} value={props.val} >{props.val}</button>
  )
}

export default Button;
